PlayerController + cambio buildCopy + mas assets
PTSD-3D/Glock-The-Clock pull request #5
Opened 2021-05-11 08:49 UTC by dagodoy

La parte de lua del PlayerController

2021-05-11 08:58 UTC, AdriAlvarez00 approved these changes
Accept(Lua)

2021-05-12 07:55 UTC, Drathijin approved these changes

2021-05-12 16:51 UTC, EstebenR requested changes
El raycast me da error en ejecucion :$, si lo quito sí me va

2021-05-13 08:14 UTC, Adrian-de-Lucas-Gomez reviewed
Teniendo la versión del motor con el raycast hecho me va bien. Me he pasado el nivel y todo

2021-05-13 11:14 UTC, Adrian-de-Lucas-Gomez approved these changes

2021-05-13 11:27 UTC, EstebenR approved these changes

2021-05-13 11:28 UTC, merged