Death zone + Respawn
PTSD-3D/Glock-The-Clock pull request #6
Opened 2021-05-12 11:37 UTC by AdriAlvarez00

### DEPENDENCIAS

-  motor = require([https://github.com/PTSD-3D/PTSD-Engine/pull/66](url))
- playerController= require([https://github.com/PTSD-3D/Glock-The-Clock/pull/5](url))

### CAMBIOS EXTRA
- Ricardo cambio las escalas para arreglar las fisicas amen
- Hemos afinado un poquito el movimiento del player

2021-05-13 08:02 UTC, dagodoy requested changes
O atraviesa el deadzone y no pasa nada, o colisiona y peta

2021-05-13 13:46 UTC, Drathijin commented
Probar con la rama del motor [colisiones-de-schrodinger](https://github.com/PTSD-3D/PTSD-Engine/pull/69) para que ya colisione siempre y no pete nunca.

2021-05-15 12:06 UTC, dagodoy approved these changes

2021-05-15 12:09 UTC, Adrian-de-Lucas-Gomez approved these changes
Mira mamá ya funciona la deadzone (niño muere brutalmente... pero hace re-spawn)

2021-05-15 12:44 UTC, EstebenR approved these changes

2021-05-15 12:45 UTC, merged